<a href="https://colab.research.google.com/github/nuraini2502/MachineLearning/blob/Praktikum4/praktikumMandiri.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Praktikum4 - Logistic Regression Calon Pembeli Mobil

Nama : Nuraini

NIM : 0110222170

Matkul : Machine Learning | Sesi Pagi

In [1]:
# import library
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Gunakan dataset Calon Pembeli Mobil Berikut ini

In [2]:
# baca data calon_pembelian_mobil.csv
from google.colab import drive
drive.mount('/content/gdrive')

path = "gdrive/MyDrive/MachineLearning/Praktikum/data/week4/"
df = pd.read_csv(path + "calonpembelimobil.csv")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [3]:
# menampilkan 5 tabel pertama
df.head()

   ID  Usia  Status  Kelamin  Memiliki_Mobil  Penghasilan  Beli_Mobil
0   1    32       1        0               0          240           1
1   2    49       2        1               1          100           0
2   3    52       1        0               2          250           1
3   4    26       2        1               1          130           0
4   5    45       3        0               2          237           1

In [4]:
# pilih fitur X dan y
X = df[['Usia','Status','Kelamin','Memiliki_Mobil','Penghasilan']]
y = df['Beli_Mobil']

In [5]:
# split data train dan test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 2. Buat model Logistic Regression!

In [6]:
# buat object model instan dari class LinearRegression
model = LogisticRegression()

# melakukan proses training
model.fit(X_train, y_train)

# prediksi hasil menggunakan data uji
y_pred = model.predict(X_test)

In [7]:
# evaluasi model
print("Akurasi:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nLaporan Klasifikasi:\n", classification_report(y_test, y_pred))

Akurasi: 0.93

Confusion Matrix:
 [[ 55   9]
 [  5 131]]

Laporan Klasifikasi:
               precision    recall  f1-score   support

           0       0.92      0.86      0.89        64
           1       0.94      0.96      0.95       136

    accuracy                           0.93       200
   macro avg       0.93      0.91      0.92       200
weighted avg       0.93      0.93      0.93       200

# 3. Gunakan dataset baru untuk menguji model!

In [8]:
# Baca dataset baru
df_new = pd.read_csv(path + 'calonpembelimobil.csv')

# Lihat 5 baris pertama dataset baru
df_new.head()

   ID  Usia  Status  Kelamin  Memiliki_Mobil  Penghasilan  Beli_Mobil
0   1    32       1        0               0          240           1
1   2    49       2        1               1          100           0
2   3    52       1        0               2          250           1
3   4    26       2        1               1          130           0
4   5    45       3        0               2          237           1

In [9]:
# memastikan kolam fitur yang digunakan untuk prediksi
X_new = df_new[['Usia','Status','Kelamin','Memiliki_Mobil','Penghasilan']]

# menambahkan kolom 'prediksi_beli_mobil'
df_new['Prediksi_Beli_Mobil'] = model.predict(X_new)

# menampilkan 5 baris pertama dataset baru
df_new.head()

,ID,Usia,Status,Kelamin,Memiliki_Mobil,Penghasilan,Beli_Mobil,Prediksi_Beli_Mobil
0,1,32,1,0,0,240,1,1
1,2,49,2,1,1,100,0,0
2,3,52,1,0,2,250,1,1
3,4,26,2,1,1,130,0,0
4,5,45,3,0,2,237,1,1

In [10]:
# evaluasi performa model pada df_new
print("Akurasi Model pada df_baru:",  accuracy_score(df_new['Beli_Mobil'], df_new['Prediksi_Beli_Mobil']))
print("\nConfusion Matrix pada df_baru:\n", confusion_matrix(df_new['Beli_Mobil'], df_new['Prediksi_Beli_Mobil']))
print("\nLaporan Klasifikasi pada df_baru:\n", classification_report(df_new['Beli_Mobil'], df_new['Prediksi_Beli_Mobil']))

Akurasi Model pada df_baru: 0.929

Confusion Matrix pada df_baru:
 [[334  33]
 [ 38 595]]

Laporan Klasifikasi pada df_baru:
               precision    recall  f1-score   support

           0       0.90      0.91      0.90       367
           1       0.95      0.94      0.94       633

    accuracy                           0.93      1000
   macro avg       0.92      0.93      0.92      1000
weighted avg       0.93      0.93      0.93      1000